name: idea_tracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # do not change to cupertino_icons to ^1.0.2 until dart enforces null safety.  This should be next flutter/dart major udpate
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+3
  get_it: ^5.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true