name: idea_tracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+3
  get_it: ^5.0.3

  # firebase plugins
  firebase_core: ^0.5.3
  firebase_auth: 0.18.4+1
  # for database
  cloud_firestore: ^0.14.4
  firebase_crashlytics: ^0.2.4
  firebase_analytics: ^6.3.0
  firebase_storage: ^5.2.0
  # Passwordless authentication with email link use:
  firebase_dynamic_links: ^0.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true